AWSTemplateFormatVersion: 2010-09-09

Description: Simple cloud formation for bucket creation and configuration

Parameters:
  BucketName:
    Type: String
    Default: "resume-bucket-unique"
  Versioning:
    Description: Set versioning option for bucket
    Default: Suspended
    Type: String
    AllowedValues: [Enabled, Suspended]


Resources:
  MainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

      VersioningConfiguration:
        Status: !Ref Versioning

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MainBucket
        PolicyDocument:
#         AccessControl: PublicRead
          Id: MyPolicy
          Version: 2012-10-17
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: !Sub "arn:aws:s3:::${MainBucket}/*"

Outputs:
  MainbucketName:
    Description: Outputs the name of the bucket
    Value: !Ref MainBucket
  MainbucketARN:
    Value: !GetAtt MainBucket.Arn
  MainbucketDomain:
    Value: !GetAtt MainBucket.DomainName
  MainbucketURL:
    Value: !GetAtt MainBucket.WebsiteURL
