AWSTemplateFormatVersion: '2010-09-09'

Description: Lambda function to interact with DynamoDB table

Parameters:
  CodeBucket:
    Type: String
    Default: "code-bucket-stack-bucket-unique"
  Code:
    Type: String
    Default: "code.zip"

Resources:

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LambdaFunction"
      Handler: code.lambda_handler
      Runtime: python3.9
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref Code
      Role: !GetAtt LambdaFunctionRole.Arn

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "LambdaFunctionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "LambdaFunctionPolicyDynamoDBAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Query"
                  - "dynamodb:UpdateItem"
                Resource: !GetAtt DynamoDBTable.Arn
        - PolicyName: "LambdaFunctionPolicyS3CodeAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::${CodeBucket}/code.zip"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "visitor-count"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "Count"
          AttributeType: "N"
        - AttributeName: "Number"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "Count"
          KeyType: "HASH"
        - AttributeName: "Number"
          KeyType: "RANGE"
